{% set name = "pyls-memestra" %}
{% set version = "0.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 13cb24edb10679916def0bf964253e17e28e17e9ee11710a971917c2d0228eea

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.4
    - pip
  run:
    - python >=3.4
    - pyyaml
    - python-language-server
    - memestra
    - deprecated
    - frilouz >=0.0.2
    - pycodestyle >=2.7.0

test:
  requires:
    - pip
  imports:
    - pyls_memestra
  commands:
    - pip check

about:
  home: https://github.com/QuantStack/pyls-memestra/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Memestra plugin for the Python Language Server

extra:
  recipe-maintainers:
    - marimeireles
    - SylvainCorlay
