{% set name = "pyls-memestra" %}
{% set version = "0.0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9ced11086134f5493fe240194bc4a0f63e253bd5e4214b58c92ed4e5ba19de3f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.4
    - pip
  run:
    - python >=3.4
    - pyyaml
    - python-language-server
    - memestra
    - deprecated
    - frilouz >=0.0.2
    # autopep8 >1.5.5 conflicts with python-language-server because of pycodestyle versions
    - autopep8 =1.5.5

test:
  requires:
    - pip
  imports:
    - pyls_memestra
  commands:
    - pip check

about:
  home: https://github.com/QuantStack/pyls-memestra/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Memestra plugin for the Python Language Server

extra:
  recipe-maintainers:
    - marimeireles
    - SylvainCorlay
